### ISSUE TITLE
`ipfs name publish --key notself` records are not renewed

### ISSUE THREAD

**Issue by wigy-opensource-developer** [DeCentral-Budapest/go-ipfs#5]
We should extend the test github.com/ipfs/go-ipfs/namesys/republisher/repub_test.go to use some other key in the keystore. Unfortunately, the republisher uses a so called keybook in the peerstore that is not backed by the keystore, so it will fail to renew.

**Comment by Kubuxu** [comment]
You should report this to ipfs/go-ipfs

**Comment by wigy-opensource-developer** [comment]
What is funny is that although they are not renewed (eol is not extended), based on the manual tests we did, republishing the same record  is not needed on the DHT with a long enough eol. I will report it as soon as I get to work.

**Comment by Kubuxu** [comment]
It is needed as it will slowly disappear from DHT as nodes go offline and online.

**Comment by wigy-opensource-developer** [comment]
Wow, that is bad news. That means we need to implement #8 , too :(

**Comment by wigy-opensource-developer** [comment]
I have reported it on https://github.com/ipfs/go-ipfs/pull/3472 that is under review anyway. I will close this issue off for now.
